wsgi/Bookmarks/urls.py
import os.path
from django.conf.urls.defaults import patterns, include, url
from bookmarks.views import *
#from django.views.generic.simple import direct_to_template
from django.contrib.auth.views import password_change, password_change_done, logout_then_login

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

site_media = os.path.join(os.path.dirname(__file__), 'site_media')

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'django_bookmarks.views.home', name='home'),
    # url(r'^django_bookmarks/', include('django_bookmarks.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),

    (r'^$', main_page),
    (r'^user/(\w+)/$', user_page),
    (r'^tag/([^\s]+)/$', tag_page),
    (r'^tag/$', tag_cloud_page),
    (r'^search/$', search_page),
    (r'^popular/$', popular_page),
    (r'^bookmark/(\d+)/$', bookmark_page),

    (r'^login/$', 'django.contrib.auth.views.login'),
    (r'^accounts/login/$', 'django.contrib.auth.views.login'),
    (r'^logout/$', logout_page),
    (r'^logout_then_login/$', logout_then_login),
    (r'^password_change/$', password_change),
    (r'^password_change_done/$', password_change_done),
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': site_media }),
    (r'^register/$', register_page),
    (r'^register/success/$', 'django.views.generic.simple.direct_to_template', { 'template': 'registration/register_success.html' }),

    (r'^save/$', bookmark_save_page),
    (r'^ajax/tag/autocomplete/$', ajax_tag_autocomplete),
    (r'^vote/$', bookmark_vote_page),
    (r'^comments/', include('django.contrib.comments.urls')),
)

wsgi/Bookmarks/bookmarks/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Link(models.Model):
    url = models.URLField(unique=True)
    def __str__(self):
        return self.url

class Bookmark(models.Model):
    title = models.CharField(max_length=200)
    user = models.ForeignKey(User)
    link = models.ForeignKey(Link)
    def __str__(self):
        return '%s, %s' % (self.user.username, self.link.url)

class Tag(models.Model):
    name = models.CharField(max_length=64, unique=True)
    bookmarks = models.ManyToManyField(Bookmark)
    def __str__(self):
        return self.name

class SharedBookmark(models.Model):
    bookmark = models.ForeignKey(Bookmark, unique=True)
    date = models.DateTimeField(auto_now_add=True)
    votes = models.IntegerField(default=1)
    users_voted = models.ManyToManyField(User)
    def __str__(self):
        return '%s, %s' % self.bookmark, self.votes

wsgi/Bookmarks/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <title>Bookmarks | {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/site_media/style.css" type="text/css" />
    <script type="text/javascript" src="/site_media/jquery.js"></script>
    {% block external %}{% endblock %}
</head>
<body>
    <div id="nav">
        {% if user.is_authenticated %}
            Welcome
            <a href="/user/{{ user.username }}/">{{ user.username }}</a> |
            <a href="/save/">Submit</a> |
            <a href="/password_change">Password</a> |
            <a href="/logout">Logout</a>
        {% else %}
            <a href="/login/">Login</a> |
            <a href="/register/">Register</a>
        {% endif %}
        <br>
        <a href="/">Home</a> |
        <a href="/popular/">Top10</a> |
        <a href="/tag/">Tags</a> |
        <a href="/search/">Search</a>
    </div>
    <h1>{% block head %}{% endblock %}</h1>
    {% block content %}{% endblock %}
</body>
</html>

wsgi/Bookmarks/templates/bookmark_list.html
{% if bookmarks %}
    <ul class="bookmarks">
        {% for bookmark in bookmarks %}
            <li>
                <a href="{{ bookmark.link.url|escape }}" class="title">{{ bookmark.title|escape }}</a>
                {% if show_edit %}
                    <a href="/save/?url={{ bookmark.link.url|urlencode }}" class="edit">[edit]</a>
                {% endif %}
                <br />
                {% if show_tags %}
                    Tags:
                    {% if bookmark.tag_set.all %}
                        <ul class="tags">
                            {% for tag in bookmark.tag_set.all %}
                                <li><a href="/tag/{{ tag.name|urlencode }}/">{{ tag.name|escape }}</a></li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        None.
                    {% endif %}
                    <br />
                {% endif %}
                {% if show_user %}
                    Posted by:
                    <a href="/user/{{ bookmark.user.username }}/" class="username">{{ bookmark.user.username }}</a>
                {% endif %}
            </li>
            <br>
        {% endfor %}
    </ul>
{% else %}
    <p>No bookmarks found.</p>
{% endif %}

wsgi/Bookmarks/templates/bookmark_page.html
{% extends "base.html" %}
{% load comments %}
{% block title %}Bookmark:{{ shared_bookmark.bookmark.title|escape }}{% endblock %}
{% block head %}
    <a href="/vote/?id={{ shared_bookmark.id }}" class="vote">[+]</a>
    <a href="{{ shared_bookmark.bookmark.link.url }}" class="title">{{ shared_bookmark.bookmark.title|escape }}</a>
{% endblock %}
{% block content %}
    Posted By:
    <a href="/user/{{ shared_bookmark.bookmark.user.username }}/" class="username">{{ shared_bookmark.bookmark.user.username }}</a> |
    <span class="vote-count">Votes: {{ shared_bookmark.votes }}</span>
    <h2>Comments</h2>
    {% get_comment_count for bookmarks.sharedbookmark shared_bookmark.id as comment_count %}
    {% get_comment_list for bookmarks.sharedbookmark shared_bookmark.id as comment_list %}
    {% for comment in comment_list %}
        <div class="comment">
            <p><b>{{ comment.user.username }}</b> said:</p>
            {{ comment.comment|escape|urlizetrunc:40|linebreaks }}
        </div>
    {% endfor %}
    <p>Number of comments: {{ comment_count }}</p>
    {% render_comment_form for bookmarks.sharedbookmark shared_bookmark.id  %}
{% endblock %}

wsgi/Bookmarks/templates/bookmark_save.html
{% extends "base.html" %}
{% block external %}
    <link rel="stylesheet" href="/site_media/jquery.autocomplete.css" type="text/css" />
    <script type="text/javascript" src="/site_media/dimensions.js"> </script>
    <script type="text/javascript" src="/site_media/jquery.bgiframe.min.js"> </script>
    <script type="text/javascript" src="/site_media/jquery.autocomplete.js"> </script>
    <script type="text/javascript" src="/site_media/tag_autocomplete.js"> </script>
{% endblock %}
{% block title %}Save Bookmark{% endblock %}
{% block head %}Save Bookmark{% endblock %}
{% block content %}
    {% include 'bookmark_save_form.html' %}
{% endblock %}

wsgi/Bookmarks/templates/bookmark_save_form.html
<form id="save-form" method="post" action="/save/">
    {{ form.as_ul }}
    <input type="submit" value="Save" />
</form>

wsgi/Bookmarks/templates/main_page.html
{% extends "base.html" %}
{% block title %}Welcome to Bookmarks{% endblock %}
{% block head %}Welcome to Bookmarks{% endblock %}
{% block content %}
    {% if user.username %}
        <p>Welcome {{ user.username }}!</p>
        <p>Here you can store and share bookmarks!</p>
        <p>Try links on top right corner :)</p>
    {% else %}
        <p>Welcome!</p>
        <p>You need to <a href="/login/">Login</a>
        before you can store and share bookmarks.</p>
        <p>Try links on top right corner :)</p>
    {% endif %}
    <h2>Recent Shared Bookmarks</h2>
    {% include 'shared_bookmark_list.html' %}
{% endblock %}

wsgi/Bookmarks/templates/popular_page.html
{% extends "base.html" %}
{% block title %}Popular Bookmarks{% endblock %}
{% block head %}Popular Bookmarks{% endblock %}
{% block content %}
    {% include 'shared_bookmark_list.html' %}
{% endblock %}

wsgi/Bookmarks/templates/search.html
{% extends "base.html" %}
{% block external %}
    <script type="text/javascript" src="/site_media/search.js"></script>
{% endblock %}
{% block title %}Search Bookmarks{% endblock %}
{% block head %}Search Bookmarks{% endblock %}
{% block content %}
    <form id="search-form" method="get" action=".">
        {{ form.as_p }}
        <input type="submit" value="Search" />
    </form>
    <div id="search-results">
        {% if show_results %}
            {% include 'bookmark_list.html' %}
        {% endif %}
    </div>
{% endblock %}

wsgi/Bookmarks/templates/shared_bookmark_list.html
{% if shared_bookmarks %}
    <ul class="bookmarks">
        {% for shared_bookmark in shared_bookmarks %}
            <li>
                <a href="/vote/?id={{ shared_bookmark.id }}" class="vote">[+]</a>
                <a href="{{ shared_bookmark.bookmark.link.url }}" class="title">{{ shared_bookmark.bookmark.title|escape }}</a>
                <br />
                Posted By:
                <a href="/user/{{ shared_bookmark.bookmark.user.username }}/" class="username">{{ shared_bookmark.bookmark.user.username }}</a> |
                <span class="vote-count">Votes: {{ shared_bookmark.votes }}</span> |
                <a href="/bookmark/{{ shared_bookmark.id}}/">Comments</a>
            </li>   
            <br>
        {% endfor %}
    </ul>
{% else %}
    <p>No bookmarks found.</p>
{% endif %}

wsgi/Bookmarks/templates/tag_cloud_page.html
{% extends "base.html" %}
{% block title %}Tag Cloud{% endblock %}
{% block head %}Tag Cloud{% endblock %}
{% block content %}
    <p>Used Tags:</p>
    <div id="tag-cloud">
        {% for tag in tags %}
            <a href="/tag/{{ tag.name|urlencode }}/" class="tag-cloud-{{ tag.weight }}">{{ tag.name|escape }}</a>
        {% endfor %}
    </div>
{% endblock %}            

wsgi/Bookmarks/templates/tag_page.html
{% extends "base.html" %}
{% block title %}Tag: {{ tag_name|escape }}{% endblock %}
{% block head %}Bookmarks for Tag: {{ tag_name|escape }}{% endblock %}
{% block content %}
    {% include "bookmark_list.html" %}
{% endblock %}

wsgi/Bookmarks/templates/user_page.html
{% extends "base.html" %}
{% block external %}
    <script type="text/javascript" src="/site_media/bookmark_edit.js"></script>
{% endblock %}
{% block title %}{{ username }}{% endblock %}
{% block head %}Bookmarks for {{ username }}{% endblock %}
{% block content %}
    {% include "bookmark_list.html" %}
{% endblock %}